/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/{locale}/builds/{brand}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fiche d'un montage
         * @description Rend toutes les tailles en une seule reponse : changer de taille a l'ecran
         *     ne doit declencher aucun appel reseau.
         */
        get: operations["builds.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BuildResource */
        BuildResource: {
            slug: string;
            model_name: string;
            variant: string | null;
            brand: {
                slug: string;
                name: string;
            };
            family: {
                key: string;
                name: string;
            };
            year: number | null;
            /** @description Un champ inconnu est declare absent, jamais omis ni estime. */
            year_label: string;
            msrp: {
                formatted: string | null;
                amount_minor: number | null;
                currency: string | null;
                source_market: string | null;
                /** @description Obligatoire des que le MSRP existe : ce n'est pas un prix local. */
                disclaimer: string;
            } | null;
            msrp_label: string | null;
            msrp_absent_reason: string | null;
            sizes: {
                label: string;
                label_alt: string | null;
                wheel_size: string | null;
                rider_height: string | null;
                rider_inseam: string | null;
                geometry: {
                    key: string;
                    label: string;
                    value_formatted: string | null;
                    value_raw: number | null;
                    unit: string | null;
                    /** @description La provenance reste visible a cote du normalise. */
                    original_value: string;
                    original_unit: string | null;
                }[];
            }[];
            components: {
                key: string;
                label: string;
                /** @description Jamais traduite : "Fox Factory 36" reste "Fox Factory 36". */
                description: string;
            }[];
            freshness: {
                last_checked_at: string;
                last_changed_at: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "builds.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
                brand: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `BuildResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BuildResource"];
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Montage introuvable.";
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
}
