/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/{locale}/bikefinder/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'arbre de questions, localise, dans sa version courante
         * @description Le front l'affiche ecran par ecran et construit le chemin des reponses ;
         *     aucun libelle, aucun critere, aucune regle ne vit cote interface.
         */
        get: operations["bikefinder.tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{locale}/bikefinder/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La shortlist du Bikefinder pour un chemin de reponses complet
         * @description `path` : les cles choisies, de la racine a une option terminale, separees
         *     par des virgules (`path=mountain,no-power,trails,budget-mid`). Un chemin
         *     inconnu, incomplet ou trop long est un 422 qui nomme la question fautive
         *     et les choix acceptes — jamais une interpretation.
         *
         *     La resolution vit dans `BikefinderTree`, la requete dans `CatalogQuery`
         *     (reutilise, pas duplique), l'ordre dans `BikefinderShortlist` : MSRP
         *     croissant, une entree par famille d'abord, prix absents en dernier.
         */
        get: operations["bikefinder.results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{locale}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogue : liste paginee, filtree, avec ses facettes
         * @description Pagination par CURSEUR et non par numero de page. Une application mobile
         *     qui defile en continu verrait, avec des numeros, une carte se dupliquer
         *     des qu'un velo est insere pendant le defilement.
         */
        get: operations["builds.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{locale}/builds/{brand}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fiche d'un montage
         * @description Rend toutes les tailles en une seule reponse : changer de taille a l'ecran
         *     ne doit declencher aucun appel reseau.
         */
        get: operations["builds.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/{locale}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comparaison de 2 a 3 velos : cartes, tailles choisies, matrice
         * @description GET et non POST : une lecture pure, sans effet de bord, dont l'URL se
         *     partage et se met en cache. Le moteur reste independant de l'interface
         *     (regle d'architecture n° 4) — il vit dans `App\Comparison\CompareMatrix`,
         *     teste unitairement hors HTTP.
         *
         *     `builds` : 2-3 paires `marque/slug` separees par des virgules.
         *     `sizes` : labels de taille alignes sur `builds`, cases vides permises
         *     (`sizes=M,,L`) — la geometrie n'est comparee que si CHAQUE velo a sa
         *     taille explicitement choisie, jamais par defaut silencieux.
         */
        get: operations["compare.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BikefinderResultsResource */
        BikefinderResultsResource: {
            version: string;
            choices: {
                key: string;
                label: string;
            }[];
            builds: components["schemas"]["BuildCardResource"][];
            alternatives: components["schemas"]["BuildCardResource"][];
            compare_url: string | null;
        };
        /** BikefinderTreeResource */
        BikefinderTreeResource: {
            version: string;
            root: string;
            questions: {
                [key: string]: {
                    /** @enum {string} */
                    kind: "tiles" | "options";
                    label: string;
                    options: {
                        key: string;
                        label: string;
                        next: string | null;
                    }[];
                };
            };
        };
        /** BuildCardResource */
        BuildCardResource: {
            slug: string;
            model_name: string;
            brand: {
                slug: string;
                name: string;
            };
            family: {
                key: string;
                name: string;
            };
            year: number | null;
            /**
             * @description Un millesime inconnu se declare. 48 velos sur 98 n'en ont pas :
             *     Specialized ne le publie pas par fiche.
             */
            year_label: string;
            /**
             * @description Formate par Laravel, dans la locale demandee. Aucun montant n'est
             *     mis en forme cote front.
             */
            msrp_formatted: string | null;
            msrp_amount_minor: number | null;
            msrp_currency: string | null;
            /** @description Un prix absent porte son libelle plutot qu'un vide, et jamais zero. */
            msrp_label: string | null;
            image: components["schemas"]["MediaResource"] | null;
            sizes: string[];
            /**
             * @description La chaine BRUTE : un mullet reste « 29"/27.5" », il ne devient pas
             *     un 29 pouces qu'il n'est pas.
             */
            wheel_size: string | null;
        };
        /** BuildResource */
        BuildResource: {
            slug: string;
            model_name: string;
            variant: string | null;
            brand: {
                slug: string;
                name: string;
            };
            family: {
                key: string;
                name: string;
            };
            year: number | null;
            /** @description Un champ inconnu est declare absent, jamais omis ni estime. */
            year_label: string;
            msrp: {
                formatted: string | null;
                amount_minor: number | null;
                currency: string | null;
                source_market: string | null;
                /** @description Obligatoire des que le MSRP existe : ce n'est pas un prix local. */
                disclaimer: string;
            } | null;
            msrp_label: string | null;
            msrp_absent_reason: string | null;
            /**
             * @description La galerie, image de tete en premier. L'ordre vient de la base,
             *     pas d'un tri cote front : c'est `order_column` qui fait foi.
             */
            images: components["schemas"]["MediaResource"][];
            geometry_chart: components["schemas"]["MediaResource"] | null;
            sizes: {
                label: string;
                label_alt: string | null;
                wheel_size: string | null;
                rider_height: string | null;
                rider_inseam: string | null;
                geometry: {
                    key: string;
                    label: string;
                    value_formatted: string | null;
                    value_raw: number | null;
                    unit: string | null;
                    /**
                     * @description La provenance reste visible a cote du normalise, deja assemblee :
                     *     le front n'a pas a decider s'il faut accoler l'unite.
                     */
                    original_formatted: string;
                    original_value: string;
                    original_unit: string | null;
                }[];
            }[];
            /**
             * @description Le resume specs cles de la tete de fiche (structure 99 Spokes) :
             *     jusqu'a 5 lignes, choisies par groupes de cles candidates — le
             *     premier composant present d'un groupe gagne. C'est une regle
             *     metier, elle vit ici et jamais dans le front. La cle exposee est
             *     celle du GROUPE (stable pour l'affichage) ; le libelle est celui
             *     du composant reellement retenu, traduit.
             */
            highlights: ({
                key: string;
                label: string;
                description: string;
            } | null)[];
            components: {
                key: string;
                /**
                 * @description "shortSpecFork" est une cle d'API Trek, pas un mot que quelqu'un
                 *     reconnait. Elle ne doit jamais arriver a l'ecran.
                 */
                label: string;
                /** @description La description, elle, n'est jamais traduite : "Fox Factory 36" reste tel quel. */
                description: string;
            }[];
            freshness: {
                last_checked_at: string;
                last_changed_at: string;
            };
        };
        /** CompareResource */
        CompareResource: {
            /**
             * @description Les mêmes cartes que le catalogue : image de tête désignée par
             *     l'API, tailles disponibles, prix formaté.
             */
            bikes: components["schemas"]["BuildCardResource"][];
            sizes_selected: (string | null)[];
            sections: {
                key: string;
                label: string;
                requires_sizes: boolean;
                hint: string | null;
                rows: {
                    key: string;
                    label: string;
                    cells: ({
                        formatted: string;
                        original: string | null;
                    } | null)[];
                    /** @enum {string} */
                    status: "same" | "differs" | "partial";
                }[];
            }[];
        };
        /** ImageSizeResource */
        ImageSizeResource: {
            url: string;
            w: number;
            h: number;
        };
        /** MediaResource */
        MediaResource: {
            id: number;
            alt: string;
            /**
             * @description Les quatre cles sont ecrites en toutes lettres, et non produites
             *     par une boucle sur BikeBuild::CONVERSIONS : Scramble lit le code
             *     pour ecrire `openapi.json`, et une cle calculee ne se transcrit
             *     pas. Un test compare cette liste a CONVERSIONS — ajouter une
             *     taille sans l'exposer ici casse la suite.
             */
            sizes: {
                thumb: components["schemas"]["ImageSizeResource"];
                card: components["schemas"]["ImageSizeResource"];
                detail: components["schemas"]["ImageSizeResource"];
                detail_2x: components["schemas"]["ImageSizeResource"];
            };
            attribution: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "bikefinder.tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `BikefinderTreeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BikefinderTreeResource"];
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        accepted: string[];
                    } | {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
    "bikefinder.results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `BikefinderResultsResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BikefinderResultsResource"];
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        accepted: string;
                    } | {
                        message: string;
                        accepted: [
                            "path"
                        ];
                    } | {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
    "builds.index": {
        parameters: {
            query?: {
                sort?: string;
            };
            header?: never;
            path: {
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Une COLLECTION DE RESSOURCES, et non un `response()->json()` monte a
             *     la main : Scramble lit le code pour ecrire `openapi.json`, et un
             *     tableau assemble a la main sort en « tableau de n'importe quoi ». Le
             *     front n'aurait alors plus le droit de s'en servir — reecrire un type
             *     d'API a la main est interdit.
             *
             *
             *
             *     Array of `BuildCardResource`
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BuildCardResource"][];
                        meta: {
                            total: number;
                            per_page: number;
                            next_cursor: string | null;
                            has_more: boolean;
                        };
                        facets: {
                            brands: {
                                key: string;
                                label: string;
                                count: number;
                            }[];
                            categories: {
                                key: string;
                                label: string;
                                count: number;
                            }[];
                            wheel_sizes: {
                                key: string;
                                label: string;
                                count: number;
                            }[];
                            price: {
                                min_minor: number;
                                max_minor: number;
                                currency: string;
                            } | null;
                        };
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        accepted: [
                            "name",
                            "price_asc",
                            "price_desc",
                            "year_desc"
                        ];
                    } | {
                        message: string;
                        accepted: {
                            /** @constant */
                            0?: "brand";
                            /** @constant */
                            1?: "category";
                            /** @constant */
                            2?: "wheel_size";
                            /** @constant */
                            3?: "price_min";
                            /** @constant */
                            4?: "price_max";
                            /** @constant */
                            5?: "year";
                            /** @constant */
                            ""?: "page";
                        };
                    } | {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
    "builds.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
                brand: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `BuildResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["BuildResource"];
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Montage introuvable.";
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
    "compare.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `CompareResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CompareResource"];
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                        accepted: {
                            [key: string]: unknown;
                        };
                    } | {
                        /** @constant */
                        message: "Un velo ne se compare pas a lui-meme : doublon dans builds.";
                    } | {
                        message: string;
                        /** @constant */
                        accepted: "builds=marque/slug,marque/slug[,marque/slug]";
                    } | {
                        message: string;
                        accepted: [
                            "builds",
                            "sizes"
                        ];
                    } | {
                        message: string;
                        served: [
                            "ar-sa",
                            "en-sa"
                        ];
                    };
                };
            };
        };
    };
}
